Repository Iridium-Development/IridiumCore, pull requests merged in 2021-06, with the labels that each got.

#1 Fix placeholder serialization issues
  plugin/src/main/java/com/iridium/iridiumcore/utils/Placeholder.java
Labels: bug

#2 Add 1.17 support
  multiversion/v1_17_R1/build.gradle.kts
  multiversion/v1_17_R1/src/main/java/com/iridium/iridiumcore/multiversion/MultiVersion_V1_17_R1.java
  multiversion/v1_17_R1/src/main/java/com/iridium/iridiumcore/nms/NMS_V1_17_R1.java
  plugin/src/main/java/com/iridium/iridiumcore/MinecraftVersion.java
  settings.gradle.kts
Labels: enhancement

#3 Version Increment & NBT-API Update
  build.gradle.kts
  plugin/build.gradle.kts
  plugin/src/main/java/com/iridium/iridiumcore/IridiumCore.java
Labels: enhancement

#4 Bump XSeries to 8.0.0
  build.gradle.kts
Labels: enhancement

#5 Fix NMS titles
  multiversion/common/src/main/java/com/iridium/iridiumcore/nms/NMS.java
  multiversion/v1_10_R1/src/main/java/com/iridium/iridiumcore/nms/NMS_V1_10_R1.java
  multiversion/v1_11_R1/src/main/java/com/iridium/iridiumcore/nms/NMS_V1_11_R1.java
  multiversion/v1_12_R1/src/main/java/com/iridium/iridiumcore/nms/NMS_V1_12_R1.java
  multiversion/v1_13_R1/src/main/java/com/iridium/iridiumcore/nms/NMS_V1_13_R1.java
  multiversion/v1_13_R2/src/main/java/com/iridium/iridiumcore/nms/NMS_V1_13_R2.java
  multiversion/v1_14_R1/src/main/java/com/iridium/iridiumcore/nms/NMS_V1_14_R1.java
  multiversion/v1_15_R1/src/main/java/com/iridium/iridiumcore/nms/NMS_V1_15_R1.java
  multiversion/v1_16_R1/src/main/java/com/iridium/iridiumcore/nms/NMS_V1_16_R1.java
  multiversion/v1_16_R2/src/main/java/com/iridium/iridiumcore/nms/NMS_V1_16_R2.java
  multiversion/v1_16_R3/src/main/java/com/iridium/iridiumcore/nms/NMS_V1_16_R3.java
  multiversion/v1_17_R1/src/main/java/com/iridium/iridiumcore/nms/NMS_V1_17_R1.java
  multiversion/v1_8_R2/src/main/java/com/iridium/iridiumcore/nms/NMS_V1_8_R2.java
  multiversion/v1_8_R3/src/main/java/com/iridium/iridiumcore/nms/NMS_V1_8_R3.java
  multiversion/v1_9_R1/src/main/java/com/iridium/iridiumcore/nms/NMS_V1_9_R1.java
  multiversion/v1_9_R2/src/main/java/com/iridium/iridiumcore/nms/NMS_V1_9_R2.java
Labels: bug

#9 Improved ItemStackUtils
  plugin/src/main/java/com/iridium/iridiumcore/utils/ItemStackUtils.java
  plugin/src/main/java/com/iridium/iridiumcore/utils/SkinUtils.java
Labels: enhancement

#10 Bump XSeries to 8.1.0
  build.gradle.kts
Labels: enhancement

#11 Bump Jackson to 2.12.3 & Use jackson-datatype-jsr310
  plugin/build.gradle.kts
Labels: enhancement

#13 Add a license
  LICENSE
Labels: enhancement

#12 Fix SkinUtils exception spam & Refactor code
  plugin/src/main/java/com/iridium/iridiumcore/utils/ItemStackUtils.java
  plugin/src/main/java/com/iridium/iridiumcore/utils/SkinUtils.java
Labels: bug, enhancement
